spring:
  profiles:
    active: test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: "server"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

app:
  base-url: http://localhost:8080
  upload-dir: ${user.dir}/src/main/resources/static/images
  python-url: http://93.127.131.80:8000/response

server:
  port: 8080

jwt:
  secret-key: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  access-token:
    expiration: 3600000
  refresh-token:
    expiration: 604800000

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/hackathon_2025
    username: root
    password: 12345
serper:
  api:
    key: "393e51974c0cd1a95a5dd3b30088a757dccc8901"
    url: "https://google.serper.dev/images"
    location: "Ukraine"
    gl: "ua"
    hl: "uk"